import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getSession } from "./lib";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Playable Factory - Todo App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
          <div className="z-10 max-w-5xl w-full items-center justify-between">
            {children}
          </div>
          {/* <pre>{JSON.stringify(session, null, 2)}</pre> */}
        </main>
      </body>
    </html>
  );
}
